name: PixelsSkyblock
load: STARTUP
version: 1.0.2
description: PixelsSkyblock
authors: [Dudullle, aaa49, mcgarret2410]
main: pixelssky.main.main
commands:
   is:
     description: Commande principale.
     aliases: [i, island]
   pxs:
     description: Commande admin.
     permission: pxs.admin