name: PixelsSkyblock
load: POSTWORLD
version: 1.0.2
description: PixelsSkyblock
authors: [Dudullle, aaa49, mcgarret2410]
main: pixelssky.main.main
depends: [Citizens]
api-version: 1.13
commands:
   is:
     description: Commande principale.
     aliases: [i, island]
   pxs:
     description: Commande admin.
     permission: pxs.admin
   gm:
     description: Commande gameMode.
     permission: pxs.admin
     aliases: [gamemode, game]
   speed:
     description: Commande speed.
     permission: pxs.admin
   fly:
     description: Commande fly.
     permission: pxs.admin
   challenge:
     description: Commande des challenges.
     aliases: [c, chal, challenges]
   spawn:
     description: Commande de teleportation au spawn.
     aliases: [s]
   tpa:
     description: Demande de teleportation a un joueur.
   tpyes:
     description: Accepter la demande de teleportation a un joueur.
     aliases: [tpaccept, tpy]
   afk:
     description: Commande d'afk.
   vanish:
     description: pour te mettre en vanish (ou un de tes amis ;) ).
     permission: pxs.admin
     aliases: [v]