name: PixelsSkyblock
load: STARTUP
version: 1.0.2
description: PixelsSkyblock
authors: [Dudullle, aaa49, mcgarret2410]
main: pixelssky.main.main
commands:
   is:
     description: Commande principale.
     aliases: [i, island]
   pxs:
     description: Commande admin.
     permission: pxs.admin
   gm:
     description: Commande gameMode.
     permission: pxs.admin
     aliases: [gamemode, game]
   speed:
     description: Commande speed.
     permission: pxs.admin
   fly:
     description: Commande fly.
     permission: pxs.admin